# Generated by Django 4.2.6 on 2023-10-13 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7bb3e3c-69b1-11ee-b892-d213399f323f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
