# Generated by Django 4.2.6 on 2023-10-15 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_users_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fefc1550-6b1b-11ee-8257-d213399f323f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
