# Generated by Django 4.2.6 on 2023-10-15 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_delete_login_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2fd8c848-6b22-11ee-a456-d213399f323f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
