# Generated by Django 4.2.6 on 2023-10-15 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0041f486-6b24-11ee-9ffe-d213399f323f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
