# Generated by Django 4.2.6 on 2023-10-15 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c99d422-6b53-11ee-ab1b-d213399f323f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
