# Generated by Django 4.2.6 on 2023-10-15 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbb437c6-6b54-11ee-a550-d213399f323f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
