# Generated by Django 4.2.6 on 2023-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0002_carpark_delete_carparks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carparks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Carpark',
        ),
    ]
