# Generated by Django 4.2.6 on 2023-10-13 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d7bb56d8-69b1-11ee-b892-d213399f323f'), primary_key=True, serialize=False)),
                ('carparks', models.CharField(max_length=1000)),
            ],
        ),
    ]
