# Generated by Django 4.2.6 on 2023-10-15 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fefc2d9c-6b1b-11ee-8257-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
