# Generated by Django 4.2.6 on 2023-10-15 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2fd8defa-6b22-11ee-a456-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
