# Generated by Django 4.2.6 on 2023-10-15 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00420ade-6b24-11ee-9ffe-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
