# Generated by Django 4.2.6 on 2023-10-15 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_alter_favorites_carparks_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbb4562a-6b54-11ee-a550-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
