# Generated by Django 4.2.6 on 2023-10-17 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0008_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('194b0338-6d03-11ee-9870-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
