# Generated by Django 4.2.6 on 2023-10-17 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0010_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bfff0656-6d0e-11ee-b9a2-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
