# Generated by Django 4.2.6 on 2023-10-17 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0011_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39299244-6d0f-11ee-a4bd-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
