# Generated by Django 4.2.6 on 2023-10-17 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0012_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8bc7bf20-6d10-11ee-92ea-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
