# Generated by Django 4.2.6 on 2023-10-18 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0013_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8aa83d06-6dd1-11ee-84e6-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
