# Generated by Django 4.2.6 on 2023-11-03 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0014_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5fb7bd0-7a2a-11ee-a2ae-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
