# Generated by Django 4.2.6 on 2023-11-05 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0015_alter_favorites_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.UUIDField(default=uuid.UUID('302e3b6c-7bc5-11ee-9444-d213399f323f'), primary_key=True, serialize=False),
        ),
    ]
